:whale: Updated googletest version from version 1.8.0 to 1.11.0
FAILED: CMakeFiles/run_all_tests.dir/executables/src/run_all_tests.cpp.o 
/usr/bin/c++ -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I/opt/share/build_ubuntu2204 -I/opt/googletest/googletest/include -I/opt/googletest/googlemock/include -isystem /opt/grpc/include -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Wno-misleading-indentation -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -std=gnu++11 -fPIC -O3 -O3 -DNDEBUG -MD -MT CMakeFiles/run_all_tests.dir/executables/src/run_all_tests.cpp.o -MF CMakeFiles/run_all_tests.dir/executables/src/run_all_tests.cpp.o.d -o CMakeFiles/run_all_tests.dir/executables/src/run_all_tests.cpp.o -c /opt/share/code/executables/src/run_all_tests.cpp
In file included from /opt/googletest/googletest/include/gtest/internal/gtest-internal.h:40,
                 from /opt/googletest/googletest/include/gtest/gtest.h:58,
                 from /opt/share/code/executables/src/run_all_tests.cpp:9:
/opt/googletest/googletest/include/gtest/internal/gtest-port.h:309:5: error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
  309 | #if _MSC_VER >= 1500
      |     ^~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors